### ISSUE TITLE
State::check_string() should return Option<String>

### ISSUE THREAD

**Issue by Azdle** [jcmoyer/rust-lua53#1]
Declared Here: https://github.com/jcmoyer/rust-lua53/blob/master/src/wrapper/state.rs#L1295

`luaL_checkstring`can return null, currently the library isn't checking for this and can cause a panic if the stack isn't checked by the application before calling. In this case it should return a `None`.

Not totally sure if `Option<>` or `Result<>` is technically correct here, but I think that `Option<>` makes slightly more sense.

**Comment by jcmoyer** [comment]
Hm, under what conditions can `luaL_checkstring` return null? It's supposed to cause a Lua panic if the argument isn't a string. If you don't want the panic behavior you should use `State::to_str` (which maps to `lua_tostring` and does return `Option<String>`).

**Comment by Azdle** [comment]
I'll admit that I'm not all that versed in Lua's C APIs and I'm not actually sure what a "Lua panic" actually is, but http://www.lua.org/manual/5.3/manual.html#lua_tolstring says

    The Lua value must be a string or a number; otherwise, the function returns NULL.

That's for `tolstring`, but `checkstring` just basically says "see `tolstring`".

Thanks for the tip on `to_str()`. I'll use that.

Out of curiosity, is there a reason that you don't use `lua_tolstring`? As far as I can tell both lua and rust handle nulls in their strings just fine.

**Comment by jcmoyer** [comment]
All of the `luaL_checkXX` functions raise a Lua error if the value on the stack isn't of type `XX`. From the Lua manual:
```
If an error happens outside any protected environment, Lua calls a panic function (see
lua_atpanic) and then calls abort, thus exiting the host application. Your panic function
can avoid this exit by never returning (e.g., doing a long jump to your own recovery point
outside Lua). 
```

As for `lua_tolstring`, I forget why exactly I omitted it. My best guess is that there's both `lua_tolstring` and `luaL_tolstring`, and I probably needed to figure out a way to resolve the name collision.

**Comment by jcmoyer** [comment]
Closing this issue because `check_string` behaves as it should. Feel free to respond if you have any more questions.
