### ISSUE TITLE
Use FromLua with an arbitrary index on the stack?

### ISSUE THREAD

**Issue by coderstephen** [jcmoyer/rust-lua53#27]
Right now, `State::to_type()` can only be used to convert the value off of the top of the stack. Shouldn't it take an index so that it can be used on any value on the stack? Or is there another issue I am unaware of preventing this?

**Comment by jcmoyer** [comment]
Yeah it looks like a design flaw on my end. I'd be happy to accept a PR that adds an index parameter.

**Comment by coderstephen** [comment]
Awesome. I'll open a PR soon.
