### ISSUE TITLE
ThreadStatus result for resume method

### ISSUE THREAD

**Issue by DenisKolodin** [jcmoyer/rust-lua53#30]
Why this method doesn't return ThreadStatus?

```rust
pub fn resume(&mut self, from: Option<&mut State>, nargs: c_int) -> c_int
```

It's easier to check the result with `.is_err()`.
Is it by design or possible to send fix with PR?

**Comment by jcmoyer** [comment]
Looks like I missed this function when I moved from `c_int` to `ThreadStatus`. I'd be happy to accept a PR to fix it.
