### ISSUE TITLE
Why is the dependency to libc at "^0.1.10"?

### ISSUE THREAD

**Issue by cjcole** [jcmoyer/rust-lua53#36]
Any reason to avoid moving to a newer version?

**Comment by jcmoyer** [comment]
That's just the version that was current at the time libc was moved out of a compiler feature gate and into a separate crate. I'm OK with it being updated if there's a compelling reason to do so.

**Comment by cjcole** [comment]
An application at libc 0.2 gets compilation errors when using functions from rust-lua53 with c_void (userdata) in the signature due to an incompatible change in the definition of c_void in libc between 0.1 and 0.2.

Will reply with an example later today.

**Comment by jcmoyer** [comment]
Fixed in 645262ca4586f04ad1a3c10c81f7d0a5802f3638.
