### ISSUE TITLE
userdata example?

### ISSUE THREAD

**Issue by tinyplasticgreyknight** [jcmoyer/rust-lua53#42]
Is there any chance we could get an example showing how to create a (full) userdata containing a rust struct and correctly set up a metatable to call methods on it?
I seem to be getting a bunch of weird segfaults, probably because I'm doing something wrong.

I think @jugglerchris was doing some work with userdata, so tagging him here.

**Comment by jcmoyer** [comment]
Does c982326c1f286774fa8d83ffe51a1a8e59588e8b help?

**Comment by tinyplasticgreyknight** [comment]
But won't the result of `Point2D::new()` get dropped before `lua_new()` returns?  I'd guess we need to do some sort of fiddling with `mem::forget()` and then set up a `__gc` metamethod to call `drop()` explicitly when the object gets collected later.

**Comment by jugglerchris** [comment]
In the above example there's no drop() to worry about.  If there is one, you need to be more careful; I'll try to extract the code I use sometime this week.

**Comment by tinyplasticgreyknight** [comment]
Poor wording on my part: I was thinking about in the general case. :-)  Look forward to seeing your approach!

**Comment by jcmoyer** [comment]
@tinyplasticgreyknight, that is correct. I don't think you need `mem::forget` as you don't have ownership of the value - Lua does. I've written an example that wraps a Vec and drops it here: https://github.com/jcmoyer/rust-lua53/blob/master/examples/userdata-with-drop/main.rs

Admittedly I am not too familiar with the super low level details of Rust so I'd like someone more experienced in that area to review it and make sure it's correct.

**Comment by jugglerchris** [comment]
That looks pretty close to what I do.  Some subtleties, though:
* I think calling `check_integer` etc. from a Rust function is potentially dangerous, since an error can unwind past a language boundary.
* It's theoretically possible for an object to be resurrected after being garbage collected (from another `__gc` method); if all you do is `drop` it, then there's a possibility of accessing it again later.  I opted to store an `Option<T>` in the userdata; in the `__gc` I use `ptr::swap` with a `None`.  If anything does manage to access the userdata after that it's relatively harmless.

**Comment by jugglerchris** [comment]
I've split out my in-development (badly documented and so on) interface into a github repo: https://github.com/jugglerchris/rlua in case it's of interest.
I store (roughly) an `Option<Box<Rc<RefCell<T>>>` in userdata, so that I can share access between Lua code and Rust, but via a `Box<Any>` so that I can verify the type before using it.

**Comment by jugglerchris** [comment]
I've just added a test for trying to access a userdata after gc to my library after the above, and *ahem* fixed the bug which made it segfault rather than raise an error.

**Comment by tinyplasticgreyknight** [comment]
@jcmoyer Okay, I played around with your `Vec` example and indeed it looks like writing the object into the raw pointer prevents it from being dropped at the end of `lua_new()`.  For some reason I didn't think that was the case.

The behaviour of raw pointers used in this way seems to be:
* the value is assumed to be still alive "somewhere", so it won't be auto-dropped when all other references go out of scope
* since rustc can't tell where the raw pointer goes out of scope, it won't be auto-dropped _ever_
* we need to manually drop it when we know it's not referenced anymore (in our case, using a `__gc` metamethod)

Phew! :-)

@jugglerchris: I was wondering if we could manually manipulate the refcount of an `Rc` (in `new` and `__gc`) to take account of lua having one reference.  It looks like `Rc` doesn't expose that sort of thing, but anyway it looks like your `Option` layer already takes care of that part anyway. :+1:

Your `RefCell` component is to help maintain borrowing rules, and if I'm reading this correctly the `Box` is only necessary because of your `Box<Any>` checking, is that right?

**Comment by jugglerchris** [comment]
I'm not sure what you mean by manually manipulating the refcount - I just store an actual `Rc` instance/clone.  The `Option` is only there to handle the access-after-__gc case sanely.

Yes, the `RefCell` is there to maintain borrowing rules, specifically when I want mutable references from both Lua and Rust, and the `Box` is for the `Box<Any>` dynamic type checks.  (I'm not sure how necessary that is - I think you'd have to try pretty hard to make that go wrong from Lua; but probably from `debug.setmetatable()`).

I think if you don't need to share objects between native Rust code and Lua (ie Lua gets full ownership), then I think you can lose all the wrapping except the `Option` for post-gc safety.

**Comment by tinyplasticgreyknight** [comment]
I think I'm talking rubbish about the refcounting above, I was thinking about some refcounting techniques I'd used in C for writing a lua module recently.

**Comment by tinyplasticgreyknight** [comment]
Using all the info we've put together, I've managed to get a working rust module of my own built and tested successfully!  Good work, everybody! :-D
