### ISSUE TITLE
`glue.c` generates incorrect integer sizes.

### ISSUE THREAD

**Issue by Parakleta** [jcmoyer/rust-lua53#43]
`glue.c` uses `c_int` for 2 byte values and `c_long` for 4 byte values which is highly unlikely to ever be correct.  Typical `c_int` values are 4 bytes on all non-16bit architectures that I am aware of and on modern 64 bit computers (most of which are LP64 class) `c_long` are 8 bytes.

The correct types to use in `glue.c`, especially since it is analysing the sizes directly, should return the correct sizes using either `i32` and `i64` or `libc::int32_t` and `libc::int64_t` (and the unsigned equivalents).  The `luaconf.h` file only doesn't use the `int32_t` types because they required an additional header file.

**Comment by jcmoyer** [comment]
Yeah I'm not sure what I was thinking when I wrote that. Thanks.
