### ISSUE TITLE
Update rust-lua53 on crates.io

### ISSUE THREAD

**Issue by hallucino** [jcmoyer/rust-lua53#74]
Hi,

is it possible to update the last version of rust-lua53 on crates.io please ?

It will allow project to compile with the latest improvement (e.g: https://github.com/Gigoteur/PX8)

Thank you

**Comment by DenisKolodin** [comment]
I think the current master is **ready to be the crate**.
I use it in production since last accepted PR. There is no bugs 👍 
I've created PR #75 to fix this issue. But only @jcmoyer has rights to publish it.

**Comment by hallucino** [comment]
Yep it can be great !

**Comment by hallucino** [comment]
Any update ? :(

**Comment by jcmoyer** [comment]
Done.

**Comment by hallucino** [comment]
Thank you !
