### ISSUE TITLE
Difference between State::to_str and State::to_str_in_place

### ISSUE THREAD

**Issue by jack-fortanix** [jcmoyer/rust-lua53#94]
The function bodies for `State::to_str` and `State::to_str_in_place` appear to be identical, as is their doc comment. I was just wondering what is the reason for having both.

https://github.com/jcmoyer/rust-lua53/blob/master/src/wrapper/state.rs#L1308

**Comment by SpaceManiac** [comment]
One uses `luaL_tolstring`, the other uses `lua_tolstring`. These have different behavior, described in the Lua manual.

**Comment by jack-fortanix** [comment]
Thank you I must have missed this when comparing the functions.
